# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-21 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cargo_description', models.CharField(blank=True, max_length=256, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Assets')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HubDst', to='hubs.Hubs')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HubSrc', to='hubs.Hubs')),
            ],
        ),
    ]
